# Generated by Django 3.0 on 2020-12-23 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название теста')),
                ('description', models.CharField(max_length=500, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=20, verbose_name='Имя пользователя')),
                ('number_of_correct_answers', models.IntegerField(verbose_name='Количество правильных ответов')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_module.Tests', verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Результат',
                'verbose_name_plural': 'Результаты',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='Вопрос')),
                ('type_of_question', models.CharField(choices=[('Выбор', 'Выборочный вариант'), ('Ввод', 'Вводимый вариант')], default='Выбор', max_length=5, verbose_name='Укажите тип ответа')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_module.Tests', verbose_name='Название теста')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=30, verbose_name='Ответы')),
                ('is_correct', models.CharField(choices=[('Да', 'Да'), ('Нет', 'Нет')], default='Нет', max_length=3, verbose_name='Верный ответ?')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_module.Questions', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
